FROM continuumio/anaconda3

ADD . /code
WORKDIR /code

# Pip 9.0.3 to avoid distutils uninstallation error
RUN pip install --upgrade --force-reinstall pip==9.0.3

RUN pip install git+https://github.com/inconvergent/iutils
# Generate filenames - can remove in main files
RUN pip install git+https://github.com/inconvergent/fn

RUN pip install -r requirements.txt

RUN apt-get update
RUN apt-get install gcc -y --fix-missing

# Need gcc before installing zonemap & twisted
RUN pip install twisted==18.9.0
RUN pip install git+https://github.com/inconvergent/zonemap

# Need this for pycairo to install from pip(!)
RUN apt-get install libcairo2-dev libjpeg-dev libgif-dev -y
RUN pip install pycairo==1.18.0

RUN python3 ./setup.py build_ext --inplace
# ENTRYPOINT [ "python", "main.py" ]
