FROM continuumio/anaconda3

ADD . /code
WORKDIR /code

# Pip 9.0.3 to avoid distutils uninstallation error
# RUN pip install --upgrade --force-reinstall pip==9.0.3

# RUN pip install git+https://github.com/inconvergent/iutils
# Generate filenames - can remove in main files
RUN pip install git+https://github.com/inconvergent/fn

RUN pip install -r requirements.txt

# install cairocffi since pycairo is crap
RUN pip install cairocffi

# hack to use cairocffi instead of crappy cairo
RUN sed -i "s|import cairo|import cairocffi as cairo|g" /opt/conda/lib/python3.7/site-packages/iutils/render/render.py

RUN apt-get update
RUN apt-get install gcc -y --fix-missing

# Need gcc before installing zonemap (& twisted?)
RUN pip install twisted==18.9.0
RUN pip install git+https://github.com/inconvergent/zonemap

RUN python3 ./setup.py build_ext --inplace
# ENTRYPOINT [ "python", "main.py" ]
